#!/bin/bash

if [ ! -f "include.sh" ]; then
  echo "Please run first ./configure"
  exit
fi

# Load variables defined in configure
source include.sh

# Delete, if any, old installation
rm -rf build install

# Run CMake to generate the build tree
$CMAKE_EXE -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DUSE_OPENMP=$USE_OPENMP -DCMAKE_COMPILE_TESTS=0 -DCMAKE_CXX_FLAGS=" -DHAVE_MPI=$USE_MPI -fPIC $OPT_LEVEL " -DCMAKE_CXX_COMPILER=$MBX_CXX -DCMAKE_C_COMPILER=$MBX_CC -H. -Bbuild 

# Compile and install
cd build
make VERBOSE=1 -j 2 CXX=$MBX_CXX CC=$MBX_CC
make install

# Build plugins
# LAMMPS
if [ ! -z $LAMMPS_HOME ]; then
  # Copy fix
  cp -r $MBX_HOME/plugins/lammps/USER-MBX $LAMMPS_HOME/src
  cp -r $MBX_HOME/plugins/lammps/Makefile.mpi_mbx $LAMMPS_HOME/src/MAKE

  # Compile lammps
  cd $LAMMPS_HOME/src
  cp USER-MBX/fix_mbx.cpp .
  cp USER-MBX/pair_mbx.cpp .
  make yes-USER-MBX yes-MOLECULE yes-KSPACE yes-RIGID yes-EXTRA-PAIR
  make mpi_mbx -j 4

  if [ $? -ne 0 ]; then
    rm style_fix.h style_pair.h
    make yes-USER-MBX yes-MOLECULE yes-KSPACE yes-RIGID yes-EXTRA-PAIR
    touch fix_mbx.* pair_mbx.*
    make mpi_mbx -j 4
    if [ $? -ne 0 ]; then
      echo "Something went wrong during LAMMPS install..."
      exit
    fi
  fi
fi
