#!/usr/bin/env python3
from __future__ import annotations

import json
import tempfile
import os
from pathlib import Path

import numpy as np
from ase import Atoms

from ase_mbx import MBXCalculator


def main() -> None:
    if not os.getenv("MBX_HOME"):
        raise RuntimeError("MBX_HOME is not set. Example: export MBX_HOME=/path/to/MBX")
    config = {
        "Note": "MBX config generated by check_energy.py",
        "MBX": {
            "box": [],
            "realspace_cutoff": 9.0,
            "twobody_cutoff": 6.5,
            "threebody_cutoff": 4.5,
            "dipole_tolerance": 1e-8,
            "dipole_max_it": 100,
            "dipole_method": "cg",
            "alpha_ewald_elec": 0.60,
            "grid_density_elec": 2.5,
            "spline_order_elec": 6,
            "alpha_ewald_disp": 0.60,
            "grid_density_disp": 2.5,
            "spline_order_disp": 6,
            "ignore_2b_poly": [],
            "ignore_3b_poly": [],
        },
    }
    json_file = None
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False)
    try:
        json.dump(config, tmp, indent=2)
        tmp.flush()
        json_file = tmp.name

        atoms = Atoms("H2O", positions=[[0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0]])
        atoms.calc = MBXCalculator(
            json_file=str(json_file),
            nat_monomers=[3],
            monomer_names=["h2o"],
            atom_names=["O", "H", "H"],
        )

        energy = atoms.get_potential_energy()
        forces = atoms.get_forces()
        print(f"Energy (eV): {energy:.6f}")
        print(f"Force norm (eV/Å): {np.linalg.norm(forces):.6f}")
    finally:
        tmp.close()
        if json_file:
            try:
                Path(json_file).unlink()
            except FileNotFoundError:
                pass


if __name__ == "__main__":
    main()
