#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import pickle
import time
from pathlib import Path

import numpy as np

from ase import units
from ase.io import read, write
from ase.md.nose_hoover_chain import NoseHooverChainNVT
from ase.md.velocitydistribution import MaxwellBoltzmannDistribution, Stationary
from ase.md.verlet import VelocityVerlet

try:
    from ase.md.nose_hoover_chain import MTKNPT, IsotropicMTKNPT
except Exception:
    MTKNPT = None
    IsotropicMTKNPT = None

from ase_mbx import MBXCalculator

ION_MONOMER_MAP = {
    "Li": "li+",
    "Na": "na+",
    "K": "k+",
    "Rb": "rb+",
    "Cs": "cs+",
    "F": "f-",
    "Cl": "cl-",
    "Br": "br-",
    "I": "i-",
}


def calculate_performance(elapsed_time, nsteps, timestep_fs, natoms):
    sim_time_ns = (nsteps * timestep_fs) / 1_000_000.0
    if elapsed_time > 0.0:
        ns_per_day = sim_time_ns / (elapsed_time / 86400.0)
        timesteps_per_s = nsteps / elapsed_time
        atom_steps_per_s = (nsteps * natoms) / elapsed_time
    else:
        ns_per_day = 0.0
        timesteps_per_s = 0.0
        atom_steps_per_s = 0.0
    hours_per_ns = (elapsed_time / 3600.0) / sim_time_ns if elapsed_time > 0.0 and sim_time_ns > 0.0 else 0.0
    return (
        f"Performance: {ns_per_day:.3f} ns/day, {hours_per_ns:.3f} hours/ns, "
        f"{timesteps_per_s:.3f} timesteps/s, {atom_steps_per_s:.3f} atom-step/s"
    )


def str_to_bool(value):
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    v = str(value).strip().lower()
    if v in {"true", "t", "1", "yes", "y"}:
        return True
    if v in {"false", "f", "0", "no", "n"}:
        return False
    raise argparse.ArgumentTypeError(f"Invalid boolean value: {value}")

def _infer_monomer_spec(symbols):
    monomer_names = []
    nat_monomers = []
    i = 0
    while i < len(symbols):
        sym = symbols[i]
        if sym == "O":
            if i + 2 >= len(symbols) or symbols[i + 1] != "H" or symbols[i + 2] != "H":
                raise ValueError("Expected O-H-H ordering for each water monomer.")
            monomer_names.append("h2o")
            nat_monomers.append(3)
            i += 3
            continue
        if sym in ION_MONOMER_MAP:
            monomer_names.append(ION_MONOMER_MAP[sym])
            nat_monomers.append(1)
            i += 1
            continue
        raise ValueError(f"Unsupported atom '{sym}' for monomer inference.")
    return monomer_names, nat_monomers


def attach_mbx_calculator(atoms, json_file, monomer_name, nat_per_monomer, mbx_home, infer_monomers):
    symbols = atoms.get_chemical_symbols()
    # Keep the explicit monomer path for systems outside the limited water/ion inference rules.
    needs_infer = infer_monomers or any(sym not in {"O", "H"} for sym in symbols)
    if needs_infer:
        monomer_names, nat_monomers = _infer_monomer_spec(symbols)
    else:
        if len(symbols) % nat_per_monomer != 0:
            raise ValueError("Atom count not divisible by nat_per_monomer.")
        nmon = len(symbols) // nat_per_monomer
        nat_monomers = [nat_per_monomer] * nmon
        monomer_names = [monomer_name] * nmon

    atoms.calc = MBXCalculator(
        json_file=str(json_file),
        nat_monomers=nat_monomers,
        monomer_names=monomer_names,
        atom_names=symbols,
        mbx_home=mbx_home,
    )


def write_mbx_json(work_path, realspace_cutoff, twobody_cutoff, threebody_cutoff, periodic):
    ewald_alpha = 0.60 if periodic else 0.0
    config = {
        "Note": "MBX config generated by mbx_md.py",
        "MBX": {
            "box": [],
            "realspace_cutoff": float(realspace_cutoff),
            "twobody_cutoff": float(twobody_cutoff),
            "threebody_cutoff": float(threebody_cutoff),
            "dipole_tolerance": 1e-8,
            "dipole_max_it": 100,
            "dipole_method": "cg",
            "alpha_ewald_elec": ewald_alpha,
            "grid_density_elec": 2.5,
            "spline_order_elec": 6,
            "alpha_ewald_disp": ewald_alpha,
            "grid_density_disp": 2.5,
            "spline_order_disp": 6,
            "ignore_2b_poly": [],
            "ignore_3b_poly": [],
        },
    }
    json_path = Path(work_path) / "mbx.json"
    with json_path.open("w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)
    return json_path


def do_md_simulation(
    work_path,
    input_file,
    total_time_ps,
    timestep_fs,
    temperature_K,
    output_interval,
    pbc,
    box_size,
    ensemble,
    pressure_bar,
    t_damp_fs,
    p_damp_fs,
    tchain,
    pchain,
    tloop,
    ploop,
    npt_coupling,
    restart_file,
    realspace_cutoff,
    twobody_cutoff,
    threebody_cutoff,
    monomer_name,
    nat_per_monomer,
    infer_monomers,
    mbx_home,
):
    ensemble = ensemble.lower().strip()
    npt_coupling = (npt_coupling or "aniso").lower().strip()
    periodic = bool(pbc)

    if ensemble == "npt" and (MTKNPT is None or IsotropicMTKNPT is None):
        raise ImportError("MTKNPT/IsotropicMTKNPT not available in this ASE version.")

    os.makedirs(work_path, exist_ok=True)
    os.chdir(work_path)

    trajectory_file = os.path.join(work_path, f"{ensemble}_trajectory.xyz")
    log_file = os.path.join(work_path, f"{ensemble}_simulation.log")
    restart_pkl = os.path.join(work_path, "restart.pkl")
    restart_xyz = os.path.join(work_path, "restart.xyz")

    nsteps = int(total_time_ps * 1000.0 / timestep_fs)

    restart_source = None
    if restart_file:
        if not os.path.exists(restart_file):
            raise FileNotFoundError(f"Restart file not found: {restart_file}")
        restart_source = restart_file

    if restart_source:
        with open(restart_source, "rb") as f:
            atoms = pickle.load(f)
    else:
        atoms = read(input_file)

    atoms.pbc = np.array([periodic, periodic, periodic], dtype=bool)

    cell = atoms.get_cell()
    has_cell = (cell is not None) and (abs(np.linalg.det(cell)) > 1e-12)
    if has_cell and (box_size is not None):
        raise ValueError("Input structure already defines a cell; omit -box_size.")
    if (not has_cell) and (box_size is not None) and periodic:
        atoms.set_cell([box_size, box_size, box_size], scale_atoms=False)
        cell = atoms.get_cell()
        has_cell = abs(np.linalg.det(cell)) > 1e-12

    json_path = write_mbx_json(
        work_path,
        realspace_cutoff,
        twobody_cutoff,
        threebody_cutoff,
        periodic=periodic,
    )

    attach_mbx_calculator(
        atoms=atoms,
        json_file=json_path,
        monomer_name=monomer_name,
        nat_per_monomer=nat_per_monomer,
        infer_monomers=infer_monomers,
        mbx_home=mbx_home,
    )

    if not restart_source:
        MaxwellBoltzmannDistribution(atoms, temperature_K=temperature_K)
        Stationary(atoms)

    if t_damp_fs is None:
        t_damp_fs = timestep_fs * 100.0

    if ensemble == "npt":
        if not periodic:
            raise ValueError("NPT requires periodic boundary conditions.")
        if not has_cell:
            raise ValueError("NPT requires a valid cell. Provide --box_size or input with Lattice.")
        if npt_coupling not in {"iso", "aniso"}:
            raise ValueError("npt_coupling must be 'iso' or 'aniso'.")

        pressure_au = pressure_bar * units.bar
        if npt_coupling == "iso":
            dyn = IsotropicMTKNPT(
                atoms,
                timestep=timestep_fs * units.fs,
                temperature_K=temperature_K,
                pressure_au=pressure_au,
                tdamp=t_damp_fs * units.fs,
                pdamp=p_damp_fs * units.fs,
                tchain=tchain,
                pchain=pchain,
                tloop=tloop,
                ploop=ploop,
            )
        else:
            dyn = MTKNPT(
                atoms,
                timestep=timestep_fs * units.fs,
                temperature_K=temperature_K,
                pressure_au=pressure_au,
                tdamp=t_damp_fs * units.fs,
                pdamp=p_damp_fs * units.fs,
                tchain=tchain,
                pchain=pchain,
                tloop=tloop,
                ploop=ploop,
            )
    elif ensemble == "nvt":
        dyn = NoseHooverChainNVT(
            atoms,
            timestep_fs * units.fs,
            temperature_K=temperature_K,
            tdamp=t_damp_fs * units.fs,
            tchain=tchain,
            tloop=tloop,
        )
    elif ensemble == "nve":
        dyn = VelocityVerlet(atoms, timestep_fs * units.fs)
    else:
        raise ValueError("ensemble must be 'nve', 'nvt', or 'npt'")

    def write_frame(a=atoms):
        write(trajectory_file, a, append=True)

    def log_energy_temp(a=atoms):
        ke = a.get_kinetic_energy()
        pe = float(a.get_potential_energy())
        temp_inst = ke / (1.5 * units.kB * len(a))
        with open(log_file, "a") as f:
            f.write(
                f"{dyn.get_number_of_steps():8d} {pe:12.6f} {ke:12.6f} {pe+ke:12.6f} {temp_inst:8.2f}\n"
            )

    def write_restart(a=atoms):
        a_save = a.copy()
        a_save.calc = None
        if os.path.exists(restart_pkl):
            os.remove(restart_pkl)
        if os.path.exists(restart_xyz):
            os.remove(restart_xyz)
        with open(restart_pkl, "wb") as f:
            pickle.dump(a_save, f)
        write(restart_xyz, a)

    if restart_source and os.path.exists(log_file):
        with open(log_file, "a") as f:
            f.write("# ---- Restart ----\n")
    else:
        with open(log_file, "w") as f:
            f.write("# Step        PE(eV)        KE(eV)     Total(eV)   Temp(K)\n")

    if (not restart_source) and os.path.exists(trajectory_file):
        os.remove(trajectory_file)

    dyn.attach(write_frame, interval=output_interval)
    dyn.attach(log_energy_temp, interval=output_interval)
    dyn.attach(write_restart, interval=output_interval)

    print("Calculating initial energy...")
    initial_pe = float(atoms.get_potential_energy())
    initial_ke = atoms.get_kinetic_energy()
    initial_temp = initial_ke / (1.5 * units.kB * len(atoms))
    print(f"Initial potential energy: {initial_pe:.6f} eV")
    print(f"Initial kinetic energy: {initial_ke:.6f} eV")
    print(f"Initial temperature: {initial_temp:.2f} K")

    print(f"\nStarting {ensemble.upper()} simulation for {nsteps} steps...")
    start_time = time.time()
    completed_steps = 0
    try:
        for i in range(nsteps):
            dyn.run(1)
            completed_steps += 1
            if (i + 1) % 1000 == 0:
                pe = float(atoms.get_potential_energy())
                ke = atoms.get_kinetic_energy()
                temp_inst = ke / (1.5 * units.kB * len(atoms))
                print(
                    f"Step {i+1:6d}/{nsteps}: PE={pe:10.3f} eV, "
                    f"KE={ke:10.3f} eV, T={temp_inst:7.1f} K"
                )
    except KeyboardInterrupt:
        print("\nSimulation interrupted by user.")
    except Exception as exc:
        print(f"\nError during simulation: {exc}")
        raise

    elapsed = time.time() - start_time
    print("\nSimulation completed!")
    print(f"Completed {completed_steps}/{nsteps} steps")
    print(f"Total wall time: {elapsed:.2f} s")
    print(calculate_performance(elapsed, completed_steps, timestep_fs, len(atoms)))

    write_restart()
    print(f"Final restart saved to: {restart_pkl} and {restart_xyz}")


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Run MBX molecular dynamics simulation (ASE; NVE/NVT/MTK-NPT)."
    )
    parser.add_argument("-work_path", default="./", help="Working directory (default: ./)")
    parser.add_argument("-init_file", dest="input_file", default="initial.xyz", help="Initial structure file")
    parser.add_argument("-sim_time", dest="sim_time", type=float, required=True, help="Simulation time (ps)")
    parser.add_argument("-time_step", dest="t_step", type=float, default=0.5, help="Timestep (fs)")
    parser.add_argument("-temp", dest="temp", type=float, default=300.0, help="Temperature (K)")
    parser.add_argument("-interval", dest="interv", type=int, default=100, help="Output interval (steps)")
    parser.add_argument("-pbc", type=str_to_bool, default=True, help="Periodic boundary conditions (true/false)")
    parser.add_argument(
        "-box_size",
        type=float,
        default=None,
        help="Optional cubic box size (Å). Error if input already defines a cell.",
    )
    parser.add_argument("-ensemble", choices=["nve", "nvt", "npt"], default="nvt", help="Ensemble")
    parser.add_argument("-pressure", dest="pressure_bar", type=float, default=1.0, help="Pressure (bar)")
    parser.add_argument(
        "-npt_coupling",
        choices=["iso", "aniso"],
        default="aniso",
        help="NPT only: 'iso' = isotropic volume-only MTK; 'aniso' = full-cell MTK.",
    )
    parser.add_argument("-t_damp", dest="t_damp_fs", type=float, default=None, help="Thermostat time constant (fs)")
    parser.add_argument(
        "-p_damp", dest="p_damp_fs", type=float, default=500.0, help="Barostat time constant (fs)"
    )
    parser.add_argument("-tchain", dest="tchain", type=int, default=3, help="Thermostat NHC length (default: 3)")
    parser.add_argument("-pchain", dest="pchain", type=int, default=3, help="Barostat NHC length (default: 3)")
    parser.add_argument("-tloop", dest="tloop", type=int, default=1, help="Thermostat subcycles (default: 1)")
    parser.add_argument("-ploop", dest="ploop", type=int, default=1, help="Barostat subcycles (default: 1)")
    parser.add_argument(
        "-restart",
        dest="restart_file",
        default=None,
        help="Optional restart .pkl path. If omitted, the run starts from -init_file.",
    )
    parser.add_argument("-monomer_name", default="h2o", help="Monomer name (default: h2o)")
    parser.add_argument("-nat_per_monomer", type=int, default=3, help="Atoms per monomer (default: 3)")
    parser.add_argument(
        "-infer_monomers",
        type=str_to_bool,
        default=True,
        help="Infer monomers from atom ordering (default: true).",
    )
    parser.add_argument(
        "-realspace_cutoff",
        type=float,
        default=9.0,
        help="MBX realspace cutoff (A).",
    )
    parser.add_argument(
        "-twobody_cutoff",
        type=float,
        default=6.5,
        help="MBX 2-body cutoff (A).",
    )
    parser.add_argument(
        "-threebody_cutoff",
        type=float,
        default=4.5,
        help="MBX 3-body cutoff (A).",
    )
    args = parser.parse_args()
    return args


if __name__ == "__main__":
    mbx_home = os.environ.get("MBX_HOME")
    if not mbx_home:
        raise RuntimeError("MBX_HOME is not set. Example: export MBX_HOME=/path/to/MBX")
    args = parse_arguments()
    do_md_simulation(
        work_path=args.work_path,
        input_file=args.input_file,
        total_time_ps=args.sim_time,
        timestep_fs=args.t_step,
        temperature_K=args.temp,
        output_interval=args.interv,
        pbc=args.pbc,
        box_size=args.box_size,
        ensemble=args.ensemble,
        pressure_bar=args.pressure_bar,
        t_damp_fs=args.t_damp_fs,
        p_damp_fs=args.p_damp_fs,
        tchain=args.tchain,
        pchain=args.pchain,
        tloop=args.tloop,
        ploop=args.ploop,
        npt_coupling=args.npt_coupling,
        restart_file=args.restart_file,
        realspace_cutoff=args.realspace_cutoff,
        twobody_cutoff=args.twobody_cutoff,
        threebody_cutoff=args.threebody_cutoff,
        monomer_name=args.monomer_name,
        nat_per_monomer=args.nat_per_monomer,
        infer_monomers=args.infer_monomers,
        mbx_home=mbx_home,
    )
