#!/bin/bash

if [ ! -f "include.sh" ]; then
  echo "Please run first ./configure"
  exit
fi

# Load variables defined in configure
source include.sh

# Create a bin folder to put executables
mkdir -p $MBX_BINDIR/MBX
mkdir -p $MBX_BINDIR/MBX+LAMMPS

# Delete, if any, old installation
rm -rf build install

# Run CMake to generate the build tree
$CMAKE_EXE -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=$USE_OPENMP -DCMAKE_COMPILE_TESTS=0 -DCMAKE_CXX_FLAGS=" -DHAVE_MPI=$USE_MPI $OPT_LEVEL " -DCMAKE_CXX_COMPILER=$MBX_CXX -DCMAKE_C_COMPILER=$MBX_CC -H. -Bbuild 

# Compile and install
cd build
make VERBOSE=1 -j 2 CXX=$MBX_CXX CC=$MBX_CC
make install

# Check if MBX has been properly installed
if [ $? -ne 0 ]; then
  echo "Something went wrong with MBX installation..."
  exit
fi

# Copy main executables of MBX to the bin folder
cp $MBX_HOME/install/bin/main/* $MBX_BINDIR/MBX

# Build plugins
# LAMMPS
if [ ! -z $LAMMPS_HOME ]; then

  # Copy fix
  cp -r $MBX_HOME/plugins/lammps/USER-MBX $LAMMPS_HOME/src
  cp -r $MBX_HOME/plugins/lammps/Makefile.mpi_mbx $LAMMPS_HOME/src/MAKE

  # Compile lammps
  cd $LAMMPS_HOME/src
  cp USER-MBX/fix_mbx.cpp .
  cp USER-MBX/pair_mbx.cpp .
  make yes-USER-MBX yes-MOLECULE yes-KSPACE yes-RIGID yes-EXTRA-PAIR
  make mpi_mbx -j 4

  if [ $? -ne 0 ]; then
    rm style_fix.h style_pair.h
    make yes-USER-MBX yes-MOLECULE yes-KSPACE yes-RIGID yes-EXTRA-PAIR
    touch fix_mbx.* pair_mbx.*
    make mpi_mbx -j 4
    if [ $? -ne 0 ]; then
      echo "Something went wrong during LAMMPS install..."
      exit
    fi
  fi

  # Move executable to bin folder
  mv lmp_mpi_mbx $MBX_BINDIR/MBX+LAMMPS
fi

# Compile PLUMED if needed
if [ ! -z $PLUMED_HOME ]; then
  # Check if PLUMED has been compiled
  if [ ! -d "$PLUMED_HOME/install" ]; then
    # PLUMED is not compiled, so we will compile it now.
    cd $PLUMED_HOME
    ./configure --prefix=$PLUMED_HOME/install --enable-modules=all CXX=$MBX_CXX CC=$MBX_CC FC=$MBX_FC
    make -j 4
    make install
    if [ $? -ne 0 ]; then 
      echo "Plumed installation failed..."
      exit
    fi
  fi

  # If LAMMPS is being compiled, compile also with PLUMED
  if [ ! -z $LAMMPS_HOME ]; then
    cd $LAMMPS_HOME/src
    make lib-plumed args="$PLUMED_HOME/install -m static"
    make yes-USER-MBX yes-MOLECULE yes-KSPACE yes-RIGID yes-EXTRA-PAIR yes-PLUMED
    make -j 4 mpi_mbx
    
    # Move exe to the bin folder
    mv lmp_mpi_mbx $MBX_BINDIR/MBX+LAMMPS/lmp_mpi_mbx_plumed
  fi
fi
    
