name: Self-Hosted Integration test

on:
  workflow_dispatch:
    inputs:
      omp:
        description: 'OpenMP threads'
        required: true
        default: "1"
        type: number

jobs:
  compile-mbxlammps:
    runs-on: [self-hosted, epyc]
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
          
      - name: MBX-install
        run: |
          module unload intel || true
          ls ${{ github.workspace }}
          
          autoreconf -fi
          ./configure CXX=g++
          make -j 4
          make install
          
          echo "MBX_HOME=${{ github.workspace }}" >> "$GITHUB_ENV"
          
      - name: LAMMPS-Install
        run: |
          module unload intel || true
          export MBX_HOME=${{ env.MBX_HOME }}
          export PKG_CONFIG_PATH=${{ env.MBX_HOME }}/lib/pkgconfig
          git clone https://github.com/lammps/lammps.git -b release
          cd lammps
          
          cmake -S cmake -B build -C ./cmake/presets/basic.cmake -D PKG_MBX=yes -D PKG_EXTRA-PAIR=yes -D BUILD_MPI=no -D CMAKE_CXX_COMPILER=g++ -D CMAKE_C_COMPILER=gcc
          cmake --build build --parallel 4

      - name: Upload MBX+LAMMPS executable
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: ${{ github.workspace }}/lammps/build/lmp
          retention-days: 1
          
  test_mbxlammps:
    strategy:
      fail-fast: false
      matrix:
        example: [256h2o, 512h2o, 1024h2o, 2048h2o, na+_bulk, ch4, ch4_h2o]
    runs-on: [self-hosted, epyc]
    needs: compile-mbxlammps
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Download executable from compilation
        uses: actions/download-artifact@v4
        with:
          name: executable
      - run: ls ${{ github.workspace }} -lth
      
      - name: testing example ${{ matrix.example }}
        run: |
          chmod u+x lmp
          ls -lth ${{ github.workspace }}/lmp
          cd ${{ github.workspace }}/plugins/lammps/examples/${{ matrix.example }}/
          export OMP_NUM_THREADS=${{ github.event.inputs.omp }}
          ${{ github.workspace }}/lmp -in in.*
      - run: ls -lth ${{ github.workspace }}/plugins/lammps/examples/${{ matrix.example }}/
      - name: log output
        run: cat ${{ github.workspace }}/plugins/lammps/examples/${{ matrix.example }}/log.lammps
      - name: Upload logfile
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.example }}_log.lammps
          path: ${{ github.workspace }}/plugins/lammps/examples/${{ matrix.example }}/log.lammps
          retention-days: 7
      - name: run validate_example.py
        run: python3 ${{ github.workspace }}/plugins/lammps/examples/validate_example.py ${{ github.workspace }}/plugins/lammps/examples/${{ matrix.example }}

